// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using restapidemo;

namespace html2approvalsflow.Migrations
{
    [DbContext(typeof(ApprovalsDBContext))]
    partial class ApprovalsDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.8");

            modelBuilder.Entity("html2approvalsflow.Models.Approval", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("comments")
                        .HasColumnType("longtext");

                    b.Property<string>("emailto")
                        .HasColumnType("longtext");

                    b.Property<string>("level")
                        .HasColumnType("longtext");

                    b.Property<string>("reqid")
                        .HasColumnType("longtext");

                    b.Property<string>("status")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("approvals");
                });

            modelBuilder.Entity("html2approvalsflow.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("companies");
                });

            modelBuilder.Entity("html2approvalsflow.Models.ResourceRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("candidate")
                        .HasColumnType("longtext");

                    b.Property<string>("position")
                        .HasColumnType("longtext");

                    b.Property<string>("team")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ResourceRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
